import {
  GARAGE_CONFIG_REFERENCE_URL,
  GARAGE_LAYOUT_DOC_URL,
} from '@/lib/garage-docs';
import { REPLICATION_TRADEOFFS } from './garage-toml-copy';

/**
 * A `garage.toml` for a cluster that does not exist yet, produced from a form.
 *
 * **This module emits text and nothing else.** It reads no cluster, calls no
 * endpoint, and — the load-bearing part — never accepts, derives or generates a
 * secret. The RPC secret and the admin token leave here as `@PLACEHOLDER@`
 * tokens with the command that produces each one on the line above, so the only
 * machine that ever holds the real value is the operator's own host.
 * `garage-toml-secrets.test.ts` is the structural guard on that: no field of
 * `GarageConfigInput` may be named like a credential, this file may not reach
 * for a random source, and no permutation of the inputs may produce output
 * with a secret-shaped run in it.
 *
 * Deliberately **not** under `lib/garage/` — every file there starts
 * `import 'server-only'` and this one is imported by a client component. Same
 * escape hatch as `garage-docs.ts` and `lib/cluster/layout-sim.ts`.
 *
 * **The emitted keys are Garage v2 spelling.** In particular the replication
 * setting is a top-level integer `replication_factor`; `replication_mode` is
 * the v0.x spelling and a current Garage will not accept it. The admin API this
 * app speaks is v2 (`docs/GarageHQ_OPENAPI.json` reports `v2.3.0`), so emitting
 * the old key would hand operators a file their binary rejects — the exact
 * failure this page exists to prevent.
 */

/** The replication factors the form offers, most-recommended first. */
export const REPLICATION_FACTORS = [3, 2, 1] as const;
export type ReplicationFactor = (typeof REPLICATION_FACTORS)[number];

/**
 * The form's state.
 *
 * Note what is *not* here: no secret, no token, no password. That absence is
 * asserted, not merely intended — see `garage-toml-secrets.test.ts`.
 *
 * `bindHost` is separate from the three ports because Garage writes a single
 * `<host>:<port>` string per listener while an operator thinks about the port.
 * One host for all three listeners rather than three: `[::]` is right for
 * essentially every deployment, and an operator who wants the admin API on a
 * private interface only is editing the generated file anyway.
 *
 * `zone`, `capacity` and `nodeCount` shape the trailing comment block only.
 * They are layout settings, not config-file settings — see
 * `LAYOUT_NOT_IN_TOML_NOTICE`.
 */
export interface GarageConfigInput {
  metadataDir: string;
  dataDir: string;
  replicationFactor: ReplicationFactor;
  bindHost: string;
  rpcPort: number;
  s3Region: string;
  s3ApiPort: number;
  /** Blank means the key is omitted entirely rather than emitted commented out. */
  s3RootDomain: string;
  adminApiPort: number;
  zone: string;
  capacity: string;
  nodeCount: number;
}

/** Defaults aimed at a three-node homelab, matching the upstream cookbook. */
export const DEFAULT_CONFIG_INPUT: GarageConfigInput = {
  metadataDir: '/var/lib/garage/meta',
  dataDir: '/var/lib/garage/data',
  replicationFactor: 3,
  bindHost: '[::]',
  rpcPort: 3901,
  s3Region: 'garage',
  s3ApiPort: 3900,
  s3RootDomain: '',
  adminApiPort: 3903,
  zone: 'home',
  capacity: '1T',
  nodeCount: 3,
};

/** The placeholders. Named so a `grep @` over the output finds all of them. */
export const RPC_SECRET_PLACEHOLDER = '@RPC_SECRET@';
export const PUBLIC_ADDR_PLACEHOLDER = '@THIS_NODE_PUBLIC_IP@';
export const ADMIN_TOKEN_PLACEHOLDER = '@ADMIN_TOKEN@';

/** The first line of the file, so the header cannot drift from the filename. */
const CONFIG_HEADER_NAME = 'garage.toml — generated by garage-ware';

const MIN_PORT = 1;
const MAX_PORT = 65535;
const MAX_NODE_COUNT = 32;

/** `1T`, `1.5T`, `2G`, or a raw byte count — what `garage layout assign -c` takes. */
const CAPACITY_PATTERN = /^\d+(\.\d+)?[kKmMgGtTpP]?$/;

function isValidPort(value: number): boolean {
  return Number.isInteger(value) && value >= MIN_PORT && value <= MAX_PORT;
}

/**
 * Everything wrong with this input, in the order an operator would hit it.
 *
 * Returns messages rather than a field map: the page renders them as a list in
 * one destructive alert, which is the planner's convention for "this plan has
 * no valid outcome" and keeps the preview honest — an invalid form still shows
 * its TOML, but with the reasons it would not start above it.
 */
export function configErrors(input: GarageConfigInput): readonly string[] {
  const errors: string[] = [];

  const paths: [label: string, value: string][] = [
    ['Metadata directory', input.metadataDir],
    ['Data directory', input.dataDir],
  ];
  for (const [label, value] of paths) {
    const trimmed = value.trim();
    if (!trimmed) {
      errors.push(`${label} is required.`);
    } else if (!trimmed.startsWith('/')) {
      errors.push(
        `${label} must be an absolute path — Garage resolves it against its own working directory, not yours.`
      );
    }
  }
  if (
    input.metadataDir.trim() &&
    input.metadataDir.trim() === input.dataDir.trim()
  ) {
    errors.push(
      'Metadata and data directories must differ. Metadata wants fast storage and data wants bulk storage; sharing one path gives up both.'
    );
  }

  if (!REPLICATION_FACTORS.includes(input.replicationFactor)) {
    errors.push('Replication factor must be 3, 2 or 1.');
  } else if (input.nodeCount < input.replicationFactor) {
    // Garage refuses to apply a layout it cannot satisfy, so catching it here
    // saves the operator a round trip to a running cluster.
    errors.push(
      `A replication factor of ${input.replicationFactor} needs at least ${input.replicationFactor} storage nodes; this plan has ${input.nodeCount}.`
    );
  }

  if (!input.bindHost.trim()) {
    errors.push(
      'Bind address is required. Use [::] to listen on every interface.'
    );
  }

  const ports: [label: string, value: number][] = [
    ['RPC port', input.rpcPort],
    ['S3 API port', input.s3ApiPort],
    ['Admin API port', input.adminApiPort],
  ];
  for (const [label, value] of ports) {
    if (!isValidPort(value)) {
      errors.push(
        `${label} must be a whole number between ${MIN_PORT} and ${MAX_PORT}.`
      );
    }
  }
  const validPorts = ports.filter(([, value]) => isValidPort(value));
  if (new Set(validPorts.map(([, value]) => value)).size < validPorts.length) {
    errors.push(
      'The RPC, S3 API and admin API ports must all differ — three listeners cannot share one port.'
    );
  }

  if (!input.s3Region.trim()) {
    errors.push(
      'S3 region is required, and must match this deployment’s GARAGE_S3_REGION.'
    );
  } else if (/\s/.test(input.s3Region.trim())) {
    errors.push('S3 region cannot contain whitespace.');
  }

  const rootDomain = input.s3RootDomain.trim();
  if (rootDomain && !rootDomain.startsWith('.')) {
    errors.push(
      'S3 root domain must start with a dot (for example .s3.example.com) — Garage matches it as a suffix of the request host.'
    );
  }

  if (!input.zone.trim()) {
    errors.push('Zone is required for the example layout commands.');
  } else if (/\s/.test(input.zone.trim())) {
    errors.push('Zone cannot contain whitespace.');
  }

  if (!CAPACITY_PATTERN.test(input.capacity.trim())) {
    errors.push(
      'Capacity must be a number with an optional unit suffix, such as 1T, 1.5T or 500G.'
    );
  }

  if (
    !Number.isInteger(input.nodeCount) ||
    input.nodeCount < 1 ||
    input.nodeCount > MAX_NODE_COUNT
  ) {
    errors.push(
      `Node count must be a whole number between 1 and ${MAX_NODE_COUNT}.`
    );
  }

  return errors;
}

/**
 * A TOML basic string.
 *
 * Hand-rolled because the alternative is shipping a TOML *serializer* to the
 * browser to write fifteen keys. The round-trip test parses the result with a
 * real parser, so an escaping bug fails the suite rather than the operator.
 */
function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

/** A one-line pointer at the reference entry for the key just emitted. */
function ref(anchor: string): string {
  return `# ${GARAGE_CONFIG_REFERENCE_URL}#${anchor}`;
}

/**
 * Word-wrap prose into `# `-prefixed comment lines.
 *
 * Only the replication tradeoff needs this — every other comment is written as
 * pre-wrapped literals. That sentence is shared verbatim with the form (it is
 * the same `REPLICATION_TRADEOFFS` entry the radio group renders), so it
 * arrives as one long string and has to be broken here rather than at the
 * source.
 */
function comment(text: string): string[] {
  const lines: string[] = [];
  let current = '#';
  for (const word of text.split(/\s+/)) {
    if (current.length + 1 + word.length > COMMENT_WIDTH) {
      lines.push(current);
      current = `# ${word}`;
    } else {
      current += ` ${word}`;
    }
  }
  lines.push(current);
  return lines;
}

const COMMENT_WIDTH = 76;
const RULE = '# ' + '─'.repeat(COMMENT_WIDTH - 2);

/**
 * The generated file.
 *
 * Every emitted key carries a comment saying what it is for and a link to its
 * anchor in the upstream reference — the anchors are verified spellings, and
 * three of them are not the key name (`#s3_api_bind_addr`, `#s3_root_domain`,
 * `#admin_api_bind_addr`), which is why they are written out rather than
 * derived.
 */
export function generateGarageToml(input: GarageConfigInput): string {
  const metadataDir = input.metadataDir.trim();
  const dataDir = input.dataDir.trim();
  const bindHost = input.bindHost.trim();
  const region = input.s3Region.trim();
  const rootDomain = input.s3RootDomain.trim();
  const zone = input.zone.trim();
  const capacity = input.capacity.trim();

  const lines: string[] = [
    `# ${CONFIG_HEADER_NAME}`,
    '#',
    '# Place this file at /etc/garage.toml on EVERY node, then fill in the',
    '# @PLACEHOLDER@ values. garage-ware does not install or run Garage; this is',
    '# a starting point you take to your own hosts.',
    '#',
    `# Reference: ${GARAGE_CONFIG_REFERENCE_URL}`,
    '',
    ...comment(REPLICATION_TRADEOFFS[input.replicationFactor]),
    ref('replication_factor'),
    `replication_factor = ${input.replicationFactor}`,
    '',
    '# Where the metadata database lives. Fast storage (an SSD) is strongly',
    '# preferred — this is the latency-sensitive half of a Garage node.',
    ref('metadata_dir'),
    `metadata_dir = ${tomlString(metadataDir)}`,
    '',
    '# Where object data blocks live. This is the bulk storage.',
    ref('data_dir'),
    `data_dir = ${tomlString(dataDir)}`,
    '',
    '# Metadata engine. LMDB is the default and the recommended choice.',
    ref('db_engine'),
    'db_engine = "lmdb"',
    '',
    '# Shared secret authenticating RPC between nodes. It must be IDENTICAL on',
    '# every node. Generate it once, yourself:',
    '#   openssl rand -hex 32',
    ref('rpc_secret'),
    `rpc_secret = ${tomlString(RPC_SECRET_PLACEHOLDER)}`,
    '',
    '# The address the RPC service listens on.',
    ref('rpc_bind_addr'),
    `rpc_bind_addr = ${tomlString(`${bindHost}:${input.rpcPort}`)}`,
    '',
    "# This node's address as OTHER nodes reach it — different on every node,",
    '# and the one line in this file you cannot copy verbatim.',
    ref('rpc_public_addr'),
    `rpc_public_addr = ${tomlString(`${PUBLIC_ADDR_PLACEHOLDER}:${input.rpcPort}`)}`,
    '',
    '# Peers contacted at startup, as <node-id>@<host>:<rpc-port>. Read a',
    "# node's id with `garage node id` on that node. Leave empty on the first",
    '# node and add the others once they exist.',
    ref('bootstrap_peers'),
    'bootstrap_peers = []',
    '',
    '[s3_api]',
    "# The region S3 clients must use. Must match this deployment's",
    '# GARAGE_S3_REGION.',
    ref('s3_region'),
    `s3_region = ${tomlString(region)}`,
    '',
    "# The S3 endpoint — what this deployment's GARAGE_S3_ENDPOINT points at.",
    ref('s3_api_bind_addr'),
    `api_bind_addr = ${tomlString(`${bindHost}:${input.s3ApiPort}`)}`,
  ];

  if (rootDomain) {
    lines.push(
      '',
      '# Enables vhost-style addressing: <bucket>' +
        rootDomain +
        ' resolves to the',
      '# bucket, alongside the path-style <endpoint>/<bucket> that always works.',
      ref('s3_root_domain'),
      `root_domain = ${tomlString(rootDomain)}`
    );
  }

  lines.push(
    '',
    '[admin]',
    '# The admin API. garage-ware talks to THIS port: it has to be reachable',
    '# from wherever garage-ware runs, and it is what GARAGE_ADMIN_URL points',
    '# at.',
    ref('admin_api_bind_addr'),
    `api_bind_addr = ${tomlString(`${bindHost}:${input.adminApiPort}`)}`,
    '',
    '# garage-ware authenticates with a token you mint once the cluster is up:',
    '#   garage admin-token create --name garage-ware',
    "# Put the result in garage-ware's GARAGE_ADMIN_TOKEN. Garage v2 discourages",
    '# the static master token below in favour of that command, so it is left',
    '# commented out — uncomment it only if you specifically want one.',
    ref('admin_token'),
    `# admin_token = ${tomlString(ADMIN_TOKEN_PLACEHOLDER)}`,
    '',
    RULE,
    '# Zone and capacity are NOT settings in this file.',
    '#',
    '# They belong to the cluster layout, assigned with the CLI once every node',
    '# is running and has joined. From any node:',
    '#',
    '#   garage status',
    '#   garage layout assign <node-key> -z <zone> -c <capacity> -t <name>',
    '#   garage layout show',
    '#   garage layout apply --version <n>',
    '#',
    `# For this ${input.nodeCount}-node plan:`,
    '#'
  );

  for (
    let i = 1;
    i <= Math.max(1, Math.min(input.nodeCount, MAX_NODE_COUNT));
    i++
  ) {
    lines.push(
      `#   garage layout assign <node${i}-key> -z ${zone} -c ${capacity} -t node${i}`
    );
  }

  lines.push(
    '#   garage layout apply --version 1',
    '#',
    `# ${GARAGE_LAYOUT_DOC_URL}`,
    RULE
  );

  return lines.join('\n') + '\n';
}

/**
 * The form's edits, as a closed set.
 *
 * Kept in this file rather than beside the page so that the *only* way to add
 * a field to the form is to add it to `GarageConfigInput` here — which is the
 * file `garage-toml-secrets.test.ts` reads, so a `rpcSecret` input cannot be
 * introduced without tripping the guard. A reducer living next to the JSX
 * would route around that.
 */
export type ConfigAction =
  | {
      type: 'set';
      field:
        | 'metadataDir'
        | 'dataDir'
        | 'bindHost'
        | 's3Region'
        | 's3RootDomain'
        | 'zone'
        | 'capacity';
      value: string;
    }
  | {
      type: 'setNumber';
      field: 'rpcPort' | 's3ApiPort' | 'adminApiPort' | 'nodeCount';
      /** `NaN` while the input is empty; `configErrors` reports it. */
      value: number;
    }
  | { type: 'setReplicationFactor'; value: ReplicationFactor }
  | { type: 'reset' };

export function configReducer(
  state: GarageConfigInput,
  action: ConfigAction
): GarageConfigInput {
  switch (action.type) {
    case 'set':
      return { ...state, [action.field]: action.value };
    case 'setNumber':
      return { ...state, [action.field]: action.value };
    case 'setReplicationFactor':
      return { ...state, replicationFactor: action.value };
    case 'reset':
      return DEFAULT_CONFIG_INPUT;
  }
}
