#!/bin/sh
#
# Container bootstrap: make a fresh `docker run` land on an instance somebody
# can actually administer.
#
# Three jobs, in order, before supervisord starts anything:
#
#   1. Ensure /data is writable by the app user (bind mounts arrive root-owned).
#   2. Ensure a PocketBase superuser exists, and that BOTH processes can see its
#      credentials. This is not optional polish: getPbAsSuperuser() needs
#      POCKETBASE_ADMIN_EMAIL/PASSWORD at runtime, and without them the cluster
#      read cache, storage invites, user-to-user transfers, cluster-event writes
#      and the admin invite flow all return 500.
#   3. Mint a one-time token the owner uses to claim the first app admin, since
#      the Admins createRule requires you to already be an admin.
#
# Everything here is idempotent — it runs on every start, not just the first.
set -eu

DATA_DIR=/data
PB_DATA_DIR="$DATA_DIR/pb_data"
SETUP_DIR="${SETUP_STATE_DIR:-$DATA_DIR/setup}"
SUPERUSER_ENV="$DATA_DIR/pb_superuser.env"
CLAIM_TOKEN_FILE="$SETUP_DIR/claim-token"
CLAIMED_MARKER="$SETUP_DIR/claimed"
APP_USER=nextjs
APP_GROUP=nodejs

log() { echo "[setup] $*"; }

# ---------------------------------------------------------------------------
# 1. Writable state
# ---------------------------------------------------------------------------
mkdir -p "$PB_DATA_DIR" "$SETUP_DIR"
chown -R "$APP_USER:$APP_GROUP" "$DATA_DIR"

# 32 chars from /dev/urandom, alphanumeric only so it survives copy/paste out of
# a log line and into a shell without quoting surprises.
random_secret() {
  head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | cut -c1-32
}

# Read one KEY='value' pair out of the generated credentials file WITHOUT
# executing it. Matches only an anchored assignment, takes the first hit, and
# strips one layer of surrounding single quotes.
read_env_value() {
  sed -n "s/^$1='\{0,1\}\(.*[^']\)'\{0,1\}\$/\1/p" "$SUPERUSER_ENV" | head -n 1
}

# ---------------------------------------------------------------------------
# 2. PocketBase superuser
# ---------------------------------------------------------------------------
GENERATED_PASSWORD=0

if [ -n "${POCKETBASE_ADMIN_EMAIL:-}" ] && [ -n "${POCKETBASE_ADMIN_PASSWORD:-}" ]; then
  : # Operator supplied both; use them verbatim.
elif [ -n "${POCKETBASE_ADMIN_EMAIL:-}" ] || [ -n "${POCKETBASE_ADMIN_PASSWORD:-}" ]; then
  # Exactly one set is a typo, not an intention. Guessing the other half would
  # either invent a credential or silently ignore the one that was given.
  echo "[setup] FATAL: set both POCKETBASE_ADMIN_EMAIL and POCKETBASE_ADMIN_PASSWORD, or neither." >&2
  exit 1
elif [ -f "$SUPERUSER_ENV" ]; then
  # Reuse what a previous boot generated, so restarts do not rotate the password
  # out from under an operator who wrote it down.
  #
  # PARSED, never sourced. This script runs as root, and `.` would execute the
  # file's contents as shell. The file lives on a volume that is bind-mounted
  # from the host and sat, in an earlier revision, in a directory owned by the
  # unprivileged app user — so anything able to write it (a compromised Next.js
  # or PocketBase process, or a host user) would have been executing as root on
  # the next restart. Reading two values with sed cannot do that.
  POCKETBASE_ADMIN_EMAIL=$(read_env_value POCKETBASE_ADMIN_EMAIL)
  POCKETBASE_ADMIN_PASSWORD=$(read_env_value POCKETBASE_ADMIN_PASSWORD)
  if [ -z "$POCKETBASE_ADMIN_EMAIL" ] || [ -z "$POCKETBASE_ADMIN_PASSWORD" ]; then
    echo "[setup] FATAL: $SUPERUSER_ENV exists but does not contain both values." >&2
    echo "[setup] Delete it to regenerate, or set both as container env." >&2
    exit 1
  fi
  export POCKETBASE_ADMIN_EMAIL POCKETBASE_ADMIN_PASSWORD
else
  # NOT admin@localhost: PocketBase's email validator rejects a single-label
  # domain, and `superuser upsert` reports that failure while still exiting 0 —
  # so the container came up cheerfully announcing a superuser that did not
  # exist, and every privileged operation 500'd.
  POCKETBASE_ADMIN_EMAIL="admin@garage-ware.local"
  POCKETBASE_ADMIN_PASSWORD="$(random_secret)"
  export POCKETBASE_ADMIN_EMAIL POCKETBASE_ADMIN_PASSWORD
  umask 077
  cat > "$SUPERUSER_ENV" <<EOF
# Generated by the garage-ware container on first boot because neither
# POCKETBASE_ADMIN_EMAIL nor POCKETBASE_ADMIN_PASSWORD was supplied.
# Set both as container env to manage them yourself; this file is then ignored.
POCKETBASE_ADMIN_EMAIL='$POCKETBASE_ADMIN_EMAIL'
POCKETBASE_ADMIN_PASSWORD='$POCKETBASE_ADMIN_PASSWORD'
EOF
  umask 022
  # root:root, not the app user. Nothing but this script reads it, and leaving
  # it app-writable is what made sourcing it dangerous in the first place.
  chown 0:0 "$SUPERUSER_ENV"
  chmod 600 "$SUPERUSER_ENV"
  GENERATED_PASSWORD=1
fi

export POCKETBASE_ADMIN_EMAIL POCKETBASE_ADMIN_PASSWORD

# Re-assert ownership every boot: the recursive chown at the top of this script
# hands all of /data to the app user, which would undo the root-only mode set
# when the file was generated.
if [ -f "$SUPERUSER_ENV" ]; then
  chown 0:0 "$SUPERUSER_ENV"
  chmod 600 "$SUPERUSER_ENV"
fi

# Idempotent, and safe on an empty data dir: `superuser upsert` bootstraps the
# app and honours --automigrate (default true), so it applies every migration
# before creating the account.
#
# --hooksDir is REQUIRED here, unintuitively. Migration
# 1786122444_created_StorageUserBalances.js calls `require`, which resolves
# against the hooks directory; without it that migration fails with "Invalid
# module", the app migrations are silently deferred to `serve` — and the
# collections snapshot they contain then wipes the superuser this command just
# created. The symptom is PocketBase printing its first-run installer link on a
# container that reported "superuser ready" seconds earlier. Loading the hooks
# costs nothing here: the command exits before any cron scheduler runs.
#
# Doing this at all suppresses that built-in installer, which otherwise prints a
# token URL pointing at 0.0.0.0:8090 — an address that is not reachable from a
# browser behind this container's nginx.
# `|| UPSERT_STATUS=$?` rather than a bare call: this script runs under `set -e`,
# so a standalone command exiting non-zero would kill the container before the
# warning below could ever run.
UPSERT_STATUS=0
su-exec "$APP_USER" /app/pb/pocketbase superuser upsert \
    "$POCKETBASE_ADMIN_EMAIL" "$POCKETBASE_ADMIN_PASSWORD" \
    --dir="$PB_DATA_DIR" \
    --hooksDir=/app/pb/pb_hooks \
    --migrationsDir=/app/pb/pb_migrations >/tmp/pb-superuser.log 2>&1 || UPSERT_STATUS=$?

# Do NOT trust the exit code alone: `superuser upsert` exits 0 even when it
# refuses the account (an invalid email address, for one). Require the success
# line, so a silent failure surfaces here instead of as a 500 on every
# privileged request later.
if [ "$UPSERT_STATUS" = "0" ] && grep -q "Successfully saved superuser" /tmp/pb-superuser.log; then
  log "PocketBase superuser ready: $POCKETBASE_ADMIN_EMAIL"
  if [ "$GENERATED_PASSWORD" = "1" ]; then
    log "  password generated — read it from $SUPERUSER_ENV (mode 0600)"
  fi
else
  echo "[setup] WARNING: could not create the PocketBase superuser." >&2
  sed 's/^/[setup]   /' /tmp/pb-superuser.log >&2 || true
  echo "[setup] Storage invites, transfers, cluster events and the cluster cache" >&2
  echo "[setup] will fail until this is fixed. See /admin/status once signed in." >&2
fi
rm -f /tmp/pb-superuser.log

# ---------------------------------------------------------------------------
# 3. Admin claim token
# ---------------------------------------------------------------------------
# The Admins collection gates its own creation, so the first admin cannot be
# made through the app. Whoever can read this container's logs can claim it —
# that is the proof of ownership. The token is only ever accepted while no admin
# exists, so a leaked one is inert the moment the instance is claimed.
CLAIM_TOKEN=""
if [ -f "$CLAIMED_MARKER" ]; then
  : # Already claimed; say nothing.
elif [ -n "${SETUP_CLAIM_TOKEN:-}" ]; then
  # Operator-supplied (k8s Secret, compose env). Never written to disk.
  CLAIM_TOKEN="$SETUP_CLAIM_TOKEN"
elif [ -f "$CLAIM_TOKEN_FILE" ]; then
  CLAIM_TOKEN="$(cat "$CLAIM_TOKEN_FILE")"
else
  CLAIM_TOKEN="$(random_secret)"
  umask 077
  printf '%s' "$CLAIM_TOKEN" > "$CLAIM_TOKEN_FILE"
  umask 022
  chown "$APP_USER:$APP_GROUP" "$CLAIM_TOKEN_FILE"
  chmod 600 "$CLAIM_TOKEN_FILE"
fi

BASE_URL="${APP_PUBLIC_URL:-http://localhost}"
BASE_URL="${BASE_URL%/}"

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------
echo "[setup] ---------------------------------------------------------------"
if [ -n "$CLAIM_TOKEN" ]; then
  log "This instance has no administrator yet. Claim it:"
  log ""
  log "  1. Open  $BASE_URL/setup"
  log "  2. Create your account"
  log "  3. Paste this claim token:"
  log ""
  log "     $CLAIM_TOKEN"
  log ""
  if [ -z "${SETUP_CLAIM_TOKEN:-}" ]; then
    log "  (also stored at $CLAIM_TOKEN_FILE)"
  fi
else
  log "Instance already claimed. Sign in at $BASE_URL/login"
fi
log ""
log "PocketBase admin UI: $BASE_URL/_/  (user $POCKETBASE_ADMIN_EMAIL)"

# Preflight: every one of these degrades a feature silently at runtime, so name
# them now rather than leaving the operator to discover it from an empty chart.
MISSING=0
warn_unset() {
  eval "value=\${$1:-}"
  if [ -z "$value" ]; then
    log "  ! $1 is not set — $2"
    MISSING=1
  fi
}
log ""
log "Configuration check:"
warn_unset GARAGE_ADMIN_URL   "cluster status, buckets, keys and metrics will not work"
warn_unset GARAGE_ADMIN_TOKEN "cluster status, buckets, keys and metrics will not work"
warn_unset GARAGE_S3_ENDPOINT "the in-app file browser and bucket connect page will error"
warn_unset APP_PUBLIC_URL     "invite and usage-alert emails will be skipped"
if [ "$MISSING" = "0" ]; then
  log "  all required variables are set"
else
  log ""
  log "  Full reference: https://github.com/make-ware/garage-ware/blob/main/docker/README.md"
fi
log ""
log "Once signed in, $BASE_URL/admin/status reports what is still misconfigured."
echo "[setup] ---------------------------------------------------------------"

echo "Starting services with Supervisor..."
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
